### ISSUE TITLE
FR: 'from_minted_value' lite version (without dict.delete(ada_policy_id))

### ISSUE THREAD

**Issue by dmitrystas** [aiken-lang/stdlib#86]
Hi, sometimes in spend/stake validators we need to check the minting/burning of a (parameterized) policy. The easiest way to do this is pattern matching, something like that

`expect [mint_policy_id] = ctx.transaction.mint |> from_minted_value |> policies`

but in this case `from_minted_value` does extra work ( `dict.delete(ada_policy_id)` ) and returns Value without ada_policy_id. 

For such cases, it would be great to have a lite `from_minted_value` version, something like that

```
pub fn from_minted_value_lite(self: MintedValue) -> Value {
  self.inner |> Value
}
```

Then it would be possible to do

`expect [_, mint_policy_id] = ctx.transaction.mint |> from_minted_value_lite |> policies`

thereby saving ~1M CPU units

**Comment by KtorZ** [comment]
Hey, thanks for the suggestion which I will politely decline for multiple reasons:

1. This would break the underlying invariant that  `Value` maintains, and thus cause a variety of issues (including potential attack vectors for validators) down the line.

2. `MintedValue` is soon to be removed. This exists only to cope with quirks from the Plutus script context that the ledger provides. This is specific to Plutus V2, and has been resolved in Plutus V3.  

3. ~1M CPU units represent 0.01% of the available execution budget. This is a step that happens only _once_ in the entire validator, so there are likely better path of optimizations to pursue. 

4. Regardless, this is getting cheaper with the next version of the stdlib, as we've added a few optimizations to `dict`. `dict.delete` in particular got a nice reduction between -5% (small dict) up to -40% (larger dict) for deletion. For that particular instance, we could even imagine not using `dict.delete` actually but simply discarding the first element in the ordered set since no bytearray can be ranked smaller than the empty bytearray (i.e. the Ada policy). That should be slightly faster than a plain `delete`.

If you want to make a PR to address (4), I'll be open to that!
